name = "WikiText"
uuid = "cb94ed24-2aa5-11e9-2529-2bbff1097334"
authors = ["David Ellison <davidehellison@gmail.com>"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]